### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by vincentcox** [1994rstefan/Spotify-Ping-Pong-API#2]
Any ideas?
<code>
module.js:340
    throw err;
          ^
Error: Cannot find module 'ws'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Users\Lolz\Downloads\Spotify-Ping-Pong-API-master\
Spotify-Ping-Pong-API-master\pongWorker.js:3:10)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
</code>

**Comment by 1994rstefan** [comment]
Hello,

sorry for the late reply.
You have to install the WebSocket Module. ( https://github.com/websockets/ws )
`npm install ws`
